### ISSUE TITLE
图片加载的问题

### ISSUE THREAD

**Issue by styhub** [csonchen/wxParse#33]
小程序在图片加载时候一直转圈无法加载出来。后台监控的报错代码如下：

undefined is not an object (evaluating 'o.templateInfo.templateId')
at (WASubContext.js:2:811970)
at E (WASubContext.js:2:67251)
at f (WASubContext.js:2:811802)
at (WASubContext.js:2:491432)
at E (WASubContext.js:2:67251)
at (WASubContext.js:2:491368)
at (WASubContext.js:2:785733)
at (WASubContext.js:2:524041)
at (WASubContext.js:2:1765190)
at (WASubContext.js:2:1765320)
at s (WASubContext.js:2:110706)
at (WASubContext.js:2:111168)
at (app-service.js:7325:1573)
at success (app-service.js:7103:1412)
at (WASubContext.js:2:1764555)
at w (WASubContext.js:2:783889)
at success (WASubContext.js:2:786045)
at h (WASubContext.js:2:111445)
at (WASubContext.js:2:112266)
at A (WASubContext.js:2:459731)
at (WASubContext.js:2:662668)
at h (WASubContext.js:2:111445)
at (WASubContext.js:2:112266)
at (WASubContext.js:2:625145)
at forEach (native code)
at value (WASubContext.js:2:625118)
at R (WASubContext.js:2:663650)
at (WASubContext.js:2:664996)
at (WASubContext.js:2:490212)
at (WAServiceMainContext.js:2:254859)
at _ (WAServiceMainContext.js:2:78159)
global code

![000](https://user-images.githubusercontent.com/55069709/102574915-efa70900-412c-11eb-90aa-ceb93eac1a42.png)

**Comment by csonchen** [comment]
> 小程序在图片加载时候一直转圈无法加载出来。后台监控的报错代码如下：
> 
> undefined is not an object (evaluating 'o.templateInfo.templateId')
> at (WASubContext.js:2:811970)
> at E (WASubContext.js:2:67251)
> at f (WASubContext.js:2:811802)
> at (WASubContext.js:2:491432)
> at E (WASubContext.js:2:67251)
> at (WASubContext.js:2:491368)
> at (WASubContext.js:2:785733)
> at (WASubContext.js:2:524041)
> at (WASubContext.js:2:1765190)
> at (WASubContext.js:2:1765320)
> at s (WASubContext.js:2:110706)
> at (WASubContext.js:2:111168)
> at (app-service.js:7325:1573)
> at success (app-service.js:7103:1412)
> at (WASubContext.js:2:1764555)
> at w (WASubContext.js:2:783889)
> at success (WASubContext.js:2:786045)
> at h (WASubContext.js:2:111445)
> at (WASubContext.js:2:112266)
> at A (WASubContext.js:2:459731)
> at (WASubContext.js:2:662668)
> at h (WASubContext.js:2:111445)
> at (WASubContext.js:2:112266)
> at (WASubContext.js:2:625145)
> at forEach (native code)
> at value (WASubContext.js:2:625118)
> at R (WASubContext.js:2:663650)
> at (WASubContext.js:2:664996)
> at (WASubContext.js:2:490212)
> at (WAServiceMainContext.js:2:254859)
> at _ (WAServiceMainContext.js:2:78159)
> global code
> 
> ![000](https://user-images.githubusercontent.com/55069709/102574915-efa70900-412c-11eb-90aa-ceb93eac1a42.png)

麻烦提供完整的html代码片段
